### ISSUE TITLE
Replace `↹` with `··`

### ISSUE THREAD

**Issue by nirpan** [prettier/eslint-plugin-prettier#102]
**What version of `eslint` are you using?**
4.18.2

**What version of `prettier` are you using?**
1.13.7

**What version of `eslint-plugin-prettier` are you using?**
2.6.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

.prettierrc.js
```js
module.exports = {
  semi: false,
  tabWidth: 2,
  singleQuote: true,
  useTabs: false
}
```

.eslintrc
```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true
  },
  extends: [
    'plugin:vue/essential',
    'standard',
    'prettier'
  ],
	plugins: ['vue', 'prettier'],
  rules: {
    'generator-star-spacing': 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'prettier/prettier': 'error'
  }
}
```

**Additional Info**
MacOS 10.13.5
Keyboard Layout: UK (British) English
Software: Visual Studio Code 1.25.0
node: 10.5.0
npm: 6.1.0

Visual Studio User settings:
```js
"editor.formatOnSave": true,
"[javascript]": {
  "editor.formatOnSave": false
},
"eslint.autoFixOnSave": true,
"eslint.alwaysShowStatus": true,
"prettier.disableLanguages": [
  "js"
],
"files.autoSave": "onFocusChange",
"git.enableSmartCommit": true,
"editor.fontSize": 14,
"editor.formatOnType": false,
"prettier.singleQuote": true,
"prettier.semi": false,
"prettier.eslintIntegration": true,
"vetur.format.defaultFormatter.html": "js-beautify-html"
```
**What source code are you linting?**
```vue
<template>
	<section id="contact-form" class="contact-form">
		<form v-if="isSent == false" class="form" @submit="onSubmit" method="post">
			<input name="name" v-model="contact.name" placeholder="NAME" type="text" autocomplete="name" required>
			<input name="email" v-model="contact.email" placeholder="EMAIL" type="email" autocomplete="email" required>
			<input name="phone" v-model="contact.phone" placeholder="PHONE" type="text" autocomplete="phone" required>
			<textarea name="enquiry" v-model="contact.enquiry" rows="4" placeholder="ENQUIRY" required></textarea>
			<div class="button-wrap">
				<button class="button" :disabled="isSending === true">Send Enquiry</button>
			</div>
		</form>

		<h3 class="thank-you" v-if="isSent"> Thank you for sending your enquiry!</h3>
	</section>

</template>

<script>
import axios from 'axios'
export default {
  name: 'ContactForm',

  data() {
    return {
      contact: {
        name: '',
        email: '',
        phone: '',
        enquiry: ''
      },
      isSending: false,
      isSent: false
    }
  },

  methods: {
    onSubmit: function(e) {
      e.preventDefault()
      const qs = require('qs')

      this.isSending = true

      axios
        .post(
          '/app.php',
          qs.stringify({
            name: this.contact.name,
            email: this.contact.email,
            phone: this.contact.phone,
            enquiry: this.contact.enquiry
          })
        )
        .then(response => {
          if (response.status === 200) {
            this.isSent = true
            this.isSending = false
          }
        })
        .catch(e => {
          console.log(e)
        })
    }
  }
}
</script>
<style lang="scss" scoped>
@import '~@/scss/main';

.contact-form {
  background: $color-black;
  color: $color-white;
  padding: 4.5rem 3.5rem;

  p,
  form {
    max-width: 66rem;
    margin: 0 auto;
  }

  form {
    margin-top: 4rem;
  }
}

.button {
  margin: 6rem 0 4rem;
  border: 0.2rem solid $color-black;
  cursor: pointer;

  &:hover {
    background: $color-black;
    color: $color-aureolin;
    border: 0.2rem solid $color-aureolin;
  }

  &:disabled,
  &:disabled:hover,
  &:disabled:focus {
    border: 1px solid $color-gray;
    background-color: $color-iron;
    color: $color-mine-shaft;
    cursor: not-allowed;
  }
}
</style>
```

**What did you expect to happen?**
I was expecting Prettier plugin to automatically fix any spacing issue on the script section of the '.vue' file as it does for the '.js' files or not throw any error. 

**What actually happened?**
During each build, it throws errors like these: Replace `↹↹↹↹↹` with `··········`. The only way to fix it is manually delete the 'tab' characters and replace them with spaces one by one.

**Comment by not-an-aardvark** [comment]
Hi,

In order to automatically fix your code, you need to run ESLint with the `--fix` flag.

**Comment by KarlFarrugia** [comment]
Hi,

I had a similar issue which was solved by toggling the **Convert Indentation to Tabs** settings in the command palette

**Comment by kempsteven** [comment]
have the same problem,

my code

```
export default new Vuex.Store({
	state: {},
	mutations: {},
	actions: {}
});
```


```
warning: Replace `↹` with `··` (prettier/prettier) at src\store.js:9:1:
   7 |  state: {},
   8 |  mutations: {},
>  9 |  actions: {}
     | ^
  10 | });
```

```
"rules": {
     "indent": [2,"tab"]
},
```

it cant be fixed by --fix flag

**Comment by BPScott** [comment]
It looks like you're configuring eslint's indent setting in a way that conflicts with prettier's opinions about tabs.

You should [configure prettier to use tabs](https://prettier.io/docs/en/options.html#tabs) and ideally use eslint-config-prettier to [disable any eslint rules that may conflict with prettier](https://github.com/prettier/eslint-config-prettier)

**Comment by ivalsaraj** [comment]
Had the same issue.

```
{
  "useTabs": false
}
```

This fixed my issue

**Comment by georgebias** [comment]
> Had the same issue.
> 
> ```
> {
>   "useTabs": false
> }
> ```
> 
> This fixed my issue

Thanks.

**Comment by sgtkuncoro** [comment]
anyone faced the same issue above and the solution above didn't resolve the issue, try following steps in this article https://medium.com/better-programming/integrating-prettier-and-eslint-with-vs-code-1d2f6fb53bc9 it's work on my side

**Comment by ayoubkhan558** [comment]
> Had the same issue.
> 
> ```
> {
>   "useTabs": false
> }
> ```
> 
> This fixed my issue

Where to put this

**Comment by truongtmnt** [comment]
Put in your .eslintrc files

**Comment by wustdong** [comment]
> > Had the same issue.
> > ```
> > {
> >   "useTabs": false
> > }
> > ```
> > 
> > 
> > This fixed my issue
> 
> Where to put this

Did you fix it? 
I put in my rules ,it didn't work for me.

**Comment by nilsdet** [comment]
@wustdong Put it in your .eslintrc "settings" section.
Such as:
`{
    "settings": {
        "useTabs": false
    }
}`

**Comment by shahbaz-projects-react** [comment]
In eslintrc,json :
`{:
"rules": {
      "prettier/prettier": [
        "error",
        {
          "endOfLine":"auto",
          "printWidth": 80,
          "trailingComma": "es5",
          "semi": false,
          "doubleQuote":true,
          "jsxSingleQuote": true,
          "singleQuote": false,
          "useTabs": false,
          "tabWidth":4
        }
      ]
    }
    }`
    The "useTabs" when set to true was contradicting "tabWidth" set to some value, so setting the useTabs to false worked out.

**Comment by bekza** [comment]
select the entire file, right click, select `Format Selection` re run the linting. worked for me.

**Comment by ahmad-lb** [comment]
> Hi,
> 
> In order to automatically fix your code, you need to run ESLint with the `--fix` flag.

This worked for me. Thanks @bekza

**Comment by aayush-goyal** [comment]
Not that it matters, but this is what worked for me:

**.eslintrc.json**
```
"rules": {
   "indent": ["error", "tab"],
   "prettier/prettier": [2, { "useTabs": true }]
}
```

**.prettierrc**
```
"tabWidth": 4
```

**Comment by hong-cai** [comment]
> Hi,
> 
> In order to automatically fix your code, you need to run ESLint with the `--fix` flag.

none of the above worked for me ,until I tried this:  
`npm run lint -- --fix`

**Comment by ReneRugaba** [comment]
npm run lint -- --fix ok for me too

**Comment by Mancancode** [comment]
> > Hi,
> > In order to automatically fix your code, you need to run ESLint with the `--fix` flag.
> 
> none of the above worked for me ,until I tried this:
> `npm run lint -- --fix`

thanks a lot this fixed it

**Comment by ikowadavies** [comment]
For those using WebStorm, this solution https://www.jetbrains.com/help/webstorm/prettier.html#ws_prettier_install worked for me,

**Comment by Davydx7** [comment]
remove "prettier" from eslintrc.js extensions/plugins, works for me

**Comment by Yemisrach15** [comment]
> Hi,
> 
> I had a similar issue which was solved by toggling the **Convert Indentation to Tabs** settings in the command palette

This worked for me except in my case it was **Convert Indentation to Spaces**

**Comment by mschipperheyn** [comment]
One thing I noticed is that vscode remembers spacing or tab based file indentation. eslint/prettier doesn't automatically convert this for some reason. So, if you been trying to resolve this for a while, you can end up in the situation that you already solved it, but you are seeing an error based on space based indentation when you think it's actually an error based on tab based indentation. The solution is to select the spaces: 4 button in the vscode bottom action bar and select "Convert indentation to Tabs".

**Comment by ricardo-passos** [comment]
The solution for was to disable and re-enable prettier extension on VSCode.

**Comment by billbrinck** [comment]
Somehow I had the wrong Prettier Extension installed. There are two Prettier extensions in the marketplace in VS Code and by installing the "Prettier - Code formatter" fixed the issue for me.

**Comment by UddeshJain** [comment]
> Not that it matters, but this is what worked for me:
> 
> **.eslintrc.json**
> 
> ```
> "rules": {
>    "indent": ["error", "tab"],
>    "prettier/prettier": [2, { "useTabs": true }]
> }
> ```
> 
> **.prettierrc**
> 
> ```
> "tabWidth": 4,
> "useTabs": true
> ```

I had same problem. Everything was working fine but my colleague was facing error. We used slightly different version of it but it works.

```
indent: ['error', 'space'],
'prettier/prettier': [2, { useTabs: false }],
```

**Comment by shinebayar-g** [comment]
This maybe a stupid comment, but I'm getting a similar error with my VSCode setup. I setup my prettier config through VSCode's User settings.
For example, this is what I have in VSCode User settings.
```json
    "prettier.printWidth": 120,
    "prettier.tabWidth": 4,
    "prettier.jsxSingleQuote": true,
    "prettier.singleQuote": true
```

But `plugin:prettier/recommended` is complaining that I'm not using double quotes, 2 spaces etc _(which is Prettier's default)_. It looks like `eslint-plugin-prettier` is not aware of my Prettier configuration through VSCode User settings. I tried enable/disable, restarting etc, none of it worked. However, putting above settings into `.prettierrc` file works.. What am I missing?

**Comment by stefanbobrowski** [comment]
If you change settings in your .eslintrc.js and/or .prettierrc, especially while running your app, sometimes VS Code bugs out.
I simply restarted my editor and this error went away.

**Comment by itchaox** [comment]
> If you change settings in your .eslintrc.js and/or .prettierrc, especially while running your app, sometimes VS Code bugs out. I simply restarted my editor and this error went away.

Thanks, i use VSCode, your solution solved my problem.

**Comment by Issam-seghir** [comment]
this is what worked for me  : 
in eslint config file 
```json
"rules": {
		"prettier/prettier": [
			"error",
			{
				"singleQuote": false,
				"endOfLine": "auto",
				"tabWidth": 4,
				"useTabs": true,
				"printWidth": 140
			}
		]
	}
```

**Comment by dspacejs** [comment]
Similar to @ricardo-passos, all I needed to do was reload VSCode with the `Developer: Reload Window` command.

**Comment by alexwilkerson** [comment]
> Similar to @ricardo-passos, all I needed to do was reload VSCode with the `Developer: Reload Window` command.

Finally! Thank you.

**Comment by Slurpgoose** [comment]
Issue is a bit old but to resolve this for me, I had to update VScode workspace settings with:
1. set default formatter to none
2. set prettier config path to my projects `.prettierrc`

**Comment by mrgoonie** [comment]
> this is what worked for me : in eslint config file
> 
> ```json
> "rules": {
> 		"prettier/prettier": [
> 			"error",
> 			{
> 				"singleQuote": false,
> 				"endOfLine": "auto",
> 				"tabWidth": 4,
> 				"useTabs": true,
> 				"printWidth": 140
> 			}
> 		]
> 	}
> ```
> 
> **Don't forget to reload vscode window with `command + p > Developer: Reload Window`**

OMG, that `Developer: Reload Window` saves me! Thanks man!
